### ISSUE TITLE
Add twig version to composer.json

### ISSUE THREAD

**Issue by zburke** [nyuhsl/data-catalog#12]
The application is incompatible with twig version 2 but version 1.x is not included in the `composer.json` file so it can be upgraded by `composer update`, which causes /add/Dataset to fail with the message, "Impossible to invoke a method ("widget_prototype") on a string variable ("default/add_dataset_admin.html.twig")." 

Here's the top of the stacktrace: 
```
in app\Resources\views\default\add_dataset_admin.html.twig at line 73   -
        <div class="col-sm-8"> 
          <a class="btn-add label label-success" data-target="add-{{ form.dataset_alternate_titles.vars.name}}">Add item</a> 
        </div> 
        <div class="add-{{ form.dataset_alternate_titles.vars.name}}" data-prototype="{{ _self.widget_prototype(form.dataset_alternate_titles, 'Remove item')|escape }}"> 
        {% for widget in form.dataset_alternate_titles %} 
          {{ _self.widget_prototype(widget, 'Remove item') }} 
        {% endfor %} 
```

**Comment by ianlamb77** [comment]
Hm, it looks like they now have _self return the template name instead of the actual template object, meaning macros have to be called differently. I'd like to support Twig 2.0+ so I'm going to merge your PR but keep this issue open until I get a chance to refactor the code properly.  Thanks!

**Comment by ianlamb77** [comment]
The forms should now support Twig ~2.0 with #17
