### ISSUE TITLE
Managed Entity entry issues

### ISSUE THREAD

**Issue by ncontaxis** [nyuhsl/data-catalog#130]
We would like to change one aspect of how new Managed Entities are entered when the cataloger is in the New Dataset side of the Admin section. Currently, if the cataloger clicks outside of the "Add New Entity" window, the window closes and the cataloger loses all information that they had added. If we could update the catalog so that the window only closes when the cataloger clicks the "x" in the top right-hand side, that would be great. However, please let us know if this update would be a significant amount of work and we can re-think it as a priority.

**Comment by ianlamb77** [comment]
Update: will be incorporated into new Symfony 4 version of catalog

**Comment by ianlamb77** [comment]
Added to Symfony4 codebase
