### ISSUE TITLE
Add Tissue/Cell Line as a subfield under Subject of Study

### ISSUE THREAD

**Issue by MelissaRat** [nyuhsl/data-catalog#158]
Metadate field: Subject of Study (Managed Entity) -- Defined as “the (strain of the) species of the subject of the study.” Current metadata subfields are limited to Species and Strain; DCCP-BS suggestion: add Tissue/Cell Line as a subfield (Free text subfield).

**Comment by ianlamb77** [comment]
addressed by #160
