### ISSUE TITLE
Installation question:

### ISSUE THREAD

**Issue by davidldl** [nyuhsl/data-catalog#3]
I am trying to do an install on Centos 7.   I installed apache, composer, solr, upgraded php to 5.6, grabbed the files from GitHub but I've got to the 7th step and there seem to be files don't exist in the repository download:
I've configured the server.xml and parameters.xml and was able to run the 'composer install', then run
"php app/console doctrine:schema:update --force".  This is where I hit a snag.

From web page: https://osf.io/vg7rn/wiki/home/   ,  numbers 7 and 10 in the instructions references files that I can't find:
SolrSchemaSample.xml, SolrUpdater.py and SolrIndexer.py don't seem to exist in the files downloaded from github.

I haven't done anything with my install of solr is that why I don't have a schema.xml file yet.    I am using
solr-6.4.1.tgz.    

Are there files missing?

**Comment by ianlamb77** [comment]
Hello, thanks for using the data catalog! As far as I know you are actually the first person to attempt to install this application outside of our institution, so I appreciate your patience as we may run into some issues. 

You are correct that these files appear to have gone missing from the most recent commits. You should still be able to use the site and enter dataset information, but you won't see any search results until Solr is set up using these files. 

I will try to get these files back up as soon as possible. Thanks!

**Comment by davidldl** [comment]
At the moment, it has this when I try to pull up the web page:

 Symfony
Search on Symfony website
Exception detected!
Solr server is reachable, but returns unexpected response. Check the full URL that is being requested
500 Internal Server Error - RuntimeException
Stack Trace

    in src/AppBundle/Entity/SearchResults.php at line 63  -
              $this->facets = (array) $this->solrResponse->facet_counts->facet_fields;
            } 
            else {
              throw new \RuntimeException('Solr server is reachable, but returns unexpected response. Check the full URL that is being requested');
            }
            $this->dateFacets   = (array) $this->solrResponse->facet_counts->facet_ranges->dataset_years->counts;
            array_unshift($this->dateFacets, 'before',$this->solrResponse->facet_counts->facet_ranges->dataset_years->before);
    at SearchResults ->__construct ('<html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 404 Not Found</title> </head> <body><h2>HTTP ERROR 404</h2> <p>Problem accessing /solr/select. Reason: <pre> Not Found</pre></p> </body> </html> ')
    in src/AppBundle/Controller/GeneralController.php at line 55  +
    at GeneralController ->indexAction (object(Request))
    at call_user_func_array (array(object(GeneralController), 'indexAction'), array(object(Request)))
    in app/bootstrap.php.cache at line 3211  +
    at HttpKernel ->handleRaw (object(Request), '1')
    in app/bootstrap.php.cache at line 3173  +
    at HttpKernel ->handle (object(Request), '1', true)
    in app/bootstrap.php.cache at line 3324  +
    at ContainerAwareHttpKernel ->handle (object(Request), '1', true)
    in app/bootstrap.php.cache at line 2514  +
    at Kernel ->handle (object(Request))
    in web/app_dev.php at line 28  +

Logs  -
1 error

    INFO - Calling the AppKernel::init() method is deprecated since version 2.3 and will be removed in 3.0. Move your logic to the constructor method instead.
    INFO - The Symfony\Component\HttpKernel\Kernel::init method is deprecated since version 2.3 and will be removed in 3.0. Move your logic to the constructor method instead.
    INFO - Calling the AppKernel::init() method is deprecated since version 2.3 and will be removed in 3.0. Move your logic to the constructor method instead.
    INFO - The Symfony\Component\HttpKernel\Kernel::init method is deprecated since version 2.3 and will be removed in 3.0. Move your logic to the constructor method instead.
    INFO - Matched route "homepage".
    INFO - Populated the TokenStorage with an anonymous Token.
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
    CRITICAL - Uncaught PHP Exception RuntimeException: "Solr server is reachable, but returns unexpected response. Check the full URL that is being requested" at /var/www/data-catalog-master/src/AppBundle/Entity/SearchResults.php line 63
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".

Stack Trace (Plain Text)  +

**Comment by ianlamb77** [comment]
Ah, right. It is not able to produce the search interface without getting certain information from Solr. I will be pushing an update either today or tomorrow and I will be sure to include the necessary files. Thanks!

**Comment by davidldl** [comment]
That sounds good.   I'll probably do a fresh reinstall with the updated repository.   I'll let you know how it goes.  I might need some pointers with the solr config.    I assume you are using Linux.   What distro are you using if so?

Thanks,
davidldl

**Comment by ianlamb77** [comment]
That's a good plan, since we have made some code updates which I'll be including in the next commits. You should be fine with any major Linux distro, both Symfony and Solr are pretty agnostic as far as I know. We've tested on Red Hat, Ubuntu and Debian. 

Feel free to email me at: ian.lamb _AT_ med _DOT_ nyu _DOT_ edu. I'm sure our librarians would be interested in getting in touch, and we can discuss the config issues further via email.

**Comment by davidldl** [comment]
I'll let you know how it goes when I continue the install from the updated repository.

**Comment by ianlamb77** [comment]
Closing this issue as conversation was continued on email.
