### ISSUE TITLE
Author Affiliation

### ISSUE THREAD

**Issue by ncontaxis** [nyuhsl/data-catalog#40]
Following the guidelines for author affiliation as discussed in October's meeting, we need to add the author affiliation to the catalog. The suggested formatting is attached. 
![details-page-2](https://user-images.githubusercontent.com/23215346/32346095-9d8a27de-bfe2-11e7-8401-5de5839cd7c8.png)

**Comment by ianlamb77** [comment]
Have decided this is no longer needed as the authors all have dropdowns with links to their institutional/bio profiles
