### ISSUE TITLE
Add php-curl requirement to documentation

### ISSUE THREAD

**Issue by ianlamb77** [nyuhsl/data-catalog#45]

**Comment by alibama** [comment]
add apt-get install php-dom to the requirements

**Comment by alibama** [comment]
add apt-get install php-mysqli to requirements (this may be redundant, just adding this since it fixed my pdo issue with php->mysql = i'm sure that postgres has a comparable install

**Comment by ianlamb77** [comment]
I added the php-curl and php-dom requirements, as well as APC (which was reported by another institution). I don't think we need to mention php-mysqli because it is fairly ubiquitous, but if other institutions report similar issues we can add it.

**Comment by alibama** [comment]
sounds good ian - my goal is just to get as close to a command line bootup as possible - perhaps a docker container might help?  I don't have a lot of experience with them, however am glad to give it a shot

**Comment by ianlamb77** [comment]
hm, that's an interesting idea. i also don't have much experience with docker but i like where you're going with it. something like that is also more generic than an AMI (i.e. it wouldn't limit them to using Amazon). a command line install would also be possible with a big Vagrant/Chef recipe, which would be even more generic than a docker container, though getting it set up initially might be a challenge.
