### ISSUE TITLE
connecting solr to data catalog

### ISSUE THREAD

**Issue by alibama** [nyuhsl/data-catalog#47]
working on an install for the university of virginia

I've got the server running here
http://54.86.50.208/web/

and solr is available http://54.86.50.208:8080/solr

the database installed properly and it seems like things are configured properly... on the parameters.yml file I've set solr as 
solrsearchr_server: 127.0.0.1:8080/solr
(it's line 70)

I'm running ubuntu and installed solr via apt-get - these instructions are accurate https://www.digitalocean.com/community/tutorials/how-to-install-solr-on-ubuntu-14-04

any ideas?  thanks

**Comment by ianlamb77** [comment]
Hi, it looks like the Solr URL might be missing a trailing slash. As a sidenote, it's very important to put Solr behind a firewall, or at least to set up the Tomcat server to only accept connections from certain IP addresses. As it is now, your Solr administration settings are publicly available. Let me know if that helps.

**Comment by alibama** [comment]
I added the trailing slash... didn't seem to resolve this - 
I'm keeping everything wide open while getting things running so that debug is simple to check - once I've got an install process that is solid I'll rebuild everything on a secure server

**Comment by ianlamb77** [comment]
You'll have to check the URL that is being constructed by the app to see where it's going wrong. Try adding a var_dump of the requestURL around line 95 of this file: https://github.com/nyuhsl/data-catalog/blob/master/src/AppBundle/Service/SolrSearchr.php

You should be able to paste that URL into a web browser and get results from Solr.

Also, this is a very old version of Solr so there could be a difference in the URL format from newer versions. If that's the case, the solution would be to upgrade to at least Solr 4.5.

**Comment by alibama** [comment]
that makes sense... i just used the solr version that came with apt-get=  i'll try upgrading that first

**Comment by ianlamb77** [comment]
It also seems from the error message you got that you're reaching the default Tomcat home page instead of a Solr core. You can see the HTML of the Tomcat page being returned in the error message.

**Comment by alibama** [comment]
ok - i've switched over to http://54.86.50.208:8983/solr/ where I've got solr 5.5.5 running on jetty as opposed to tomcat - 

i used this documentation https://www.digitalocean.com/community/tutorials/how-to-install-solr-5-2-1-on-ubuntu-14-04 and found it simple.... I do wonder, however, if at this point there is some issue with multiple versions having been installed on this machine and am going to scrub the whole thing and start over....   it's not a big deal, and this time i'll get an ami snapshot before i get too far down the road

**Comment by alibama** [comment]
http://ddi.hsl.virginia.edu/web/ is the new home for this project - it is a 100% clean install with solr 5.5.5 running (still publicly available here http://ddi.hsl.virginia.edu:8983/solr/ ) 

I've tested using 
127.0.0.1:8983/solr/
localhost:8983/solr/ 

and without the trailing slash.... 

for a quick install here's the stack for apt-get on a clean ubuntu 16 server
 apt-get install php-curl libapache2-mod-php php-curl php-cli git mysql-server php-mysqli

**Comment by ianlamb77** [comment]
Closing this issue because I believe this has been solved, feel free to reopen if necessary.
