### ISSUE TITLE
Timeframe Displaying Records Incorrectly

### ISSUE THREAD

**Issue by gompers100** [nyuhsl/data-catalog#72]
UMB is experiencing the following issues related to the Timeline feature.

![screenie](https://user-images.githubusercontent.com/4527480/38376563-cd15a7dc-38c6-11e8-8f20-823bb14e342b.jpg)

Problem #1: Timeframe ranges subsequent to 1995-2004

Problem #2: Timeframe 1975-1984 has a “1”, but we have no records within that range. Clicking on it results in “Sorry, this search returned no results”

Problem #3: Timeframe 1985-1994 has a “2”, but when you click on it you get a single hit

Problem #4: Timeframe 1995-2004 has a “6”, but when you click on it you get only 2 records: The first record is the same one you get when you click on the 1985-1993 timeframe. It has dates of 1993-2010

Currently, there are 8 “public” records with the following “collection years”:

2 - with no years
1 - 1993-2010
1 – 2000-2014
1 – 2010-2011
1 – 2015-2015
2 – 2016-2017

**Comment by ianlamb77** [comment]
Addressed by #73 and #76
