### ISSUE TITLE
WCAG/Section 508 compliance issues

### ISSUE THREAD

**Issue by jmarchewka** [nyuhsl/data-catalog#96]
Three issues were identified.
- skip link needed: https://webaim.org/techniques/skipnav/
- provide a label element for the "Search here to find large public and licensed datasets" search form in the header
- specify the lang attribute of the HTML element: https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-doc-lang-id.html

**Comment by ianlamb77** [comment]
addressed by #99
